"""init_search_history

Revision ID: d6577419c9f8
Revises: 
Create Date: 2026-04-21 17:42:54.444386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6577419c9f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('clean_query', sa.Text(), nullable=False),
    sa.Column('resolved_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('price_tier', sa.String(length=20), nullable=True),
    sa.Column('avg_price_at_search', sa.Float(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('was_added', sa.Integer(), nullable=False),
    sa.Column('first_searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_clean_query'), 'search_history', ['clean_query'], unique=False)
    op.create_index(op.f('ix_search_history_last_searched_at'), 'search_history', ['last_searched_at'], unique=False)
    op.drop_index('ix_sold_listings_part_id', table_name='sold_listings', if_exists=True)
    op.drop_index('ix_sold_listings_sold_date', table_name='sold_listings', if_exists=True)
    op.drop_index('ix_sold_part_date_clean', table_name='sold_listings', if_exists=True)
    op.drop_table('sold_listings', if_exists=True)
    op.drop_index('ix_active_listings_fetched_at', table_name='active_listings', if_exists=True)
    op.drop_index('ix_active_listings_part_id', table_name='active_listings', if_exists=True)
    op.drop_table('active_listings', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_listings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ebay_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('listing_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('listing_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_buy_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('margin_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_deal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['tracked_parts.id'], name='active_listings_part_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='active_listings_pkey')
    )
    op.create_index('ix_active_listings_part_id', 'active_listings', ['part_id'], unique=False)
    op.create_index('ix_active_listings_fetched_at', 'active_listings', ['fetched_at'], unique=False)
    op.create_table('sold_listings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ebay_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sold_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sold_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('listing_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_outlier', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('outlier_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_used_in_avg', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['tracked_parts.id'], name='sold_listings_part_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sold_listings_pkey'),
    sa.UniqueConstraint('ebay_item_id', name='sold_listings_ebay_item_id_key')
    )
    op.create_index('ix_sold_part_date_clean', 'sold_listings', ['part_id', 'sold_date', 'is_used_in_avg'], unique=False)
    op.create_index('ix_sold_listings_sold_date', 'sold_listings', ['sold_date'], unique=False)
    op.create_index('ix_sold_listings_part_id', 'sold_listings', ['part_id'], unique=False)
    op.drop_index(op.f('ix_search_history_last_searched_at'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_clean_query'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
