"""add_scraped_cache

Revision ID: fdbb4e9a14e4
Revises: d6577419c9f8
Create Date: 2026-04-22 15:53:05.238825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdbb4e9a14e4'
down_revision: Union[str, None] = 'd6577419c9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_sold_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ebay_item_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sold_price', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('sold_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('listing_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_sold_listings_scraped_at'), 'scraped_sold_listings', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_scraped_sold_listings_search_query'), 'scraped_sold_listings', ['search_query'], unique=False)

    op.drop_index('ix_active_listings_fetched_at', table_name='active_listings')
    op.drop_index('ix_active_listings_part_id', table_name='active_listings')
    op.drop_table('active_listings')
    op.drop_index('ix_sold_listings_part_id', table_name='sold_listings')
    op.drop_index('ix_sold_listings_sold_date', table_name='sold_listings')
    op.drop_index('ix_sold_part_date_clean', table_name='sold_listings')
    op.drop_table('sold_listings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_sold_listings_search_query'), table_name='scraped_sold_listings')
    op.drop_index(op.f('ix_scraped_sold_listings_scraped_at'), table_name='scraped_sold_listings')
    op.drop_table('scraped_sold_listings')

    op.create_table('sold_listings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ebay_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sold_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sold_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('listing_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_outlier', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('outlier_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_used_in_avg', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['tracked_parts.id'], name='sold_listings_part_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sold_listings_pkey'),
    sa.UniqueConstraint('ebay_item_id', name='sold_listings_ebay_item_id_key')
    )
    op.create_index('ix_sold_part_date_clean', 'sold_listings', ['part_id', 'sold_date', 'is_used_in_avg'], unique=False)
    op.create_index('ix_sold_listings_sold_date', 'sold_listings', ['sold_date'], unique=False)
    op.create_index('ix_sold_listings_part_id', 'sold_listings', ['part_id'], unique=False)
    op.create_table('active_listings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ebay_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('listing_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('listing_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_buy_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('margin_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_deal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['tracked_parts.id'], name='active_listings_part_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='active_listings_pkey')
    )
    op.create_index('ix_active_listings_part_id', 'active_listings', ['part_id'], unique=False)
    op.create_index('ix_active_listings_fetched_at', 'active_listings', ['fetched_at'], unique=False)
    # ### end Alembic commands ###
